'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/recommend-relevant-youtube-videos.ts';
import '@/ai/flows/html-to-pdf.ts';
import '@/ai/flows/compress-pdf.ts';
import '@/ai/flows/pdf-to-docx.ts';
import '@/ai/flows/pdf-to-html.ts';
import '@/ai/flows/pdf-to-jpg.ts';
import '@/ai/flows/pdf-to-png.ts';
import '@/ai/flows/merge-pdf.ts';
import '@/ai/flows/pdf-ocr.ts';
import '@/ai/flows/pdf-to-pptx.ts';
import '@/ai/flows/split-pdf.ts';
import '@/aiflows/pdf-to-svg.ts';
import '@/ai/flows/pdf-to-text.ts';
import '@/ai/flows/watermark-pdf.ts';
import '@/ai/flows/pptx-to-pdf.ts';
import '@/ai/flows/web-to-pdf.ts';
import '@/ai/flows/bmp-to-pdf.ts';
import '@/ai/flows/djvu-to-pdf.ts';
import '@/ai/flows/doc-to-pdf.ts';
import '@/ai/flows/dot-to-pdf.ts';
import '@/ai/flows/xltx-to-pdf.ts';
import '@/ai/flows/xlsb-to-pdf.ts';
import '@/ai/flows/xls-to-pdf.ts';
